= Scriptless Scripts with ECDSA
Lloyd Fournier <lloyd@coblox.tech>;
:toc:
:revdate: 16-05-2019

NOTE: Author: {authors} +
Date: {revdate} +
Issue: https://github.com/comit-network/comit-rs/issues/899

== Context

<<Sanchez18a>> describes a scriptless scripts protocol that can be used to replace HTLCs with conditional payments based on learning a discrete logarithm (rather than a hash pre-image).
This would make atomic swaps indistinguishable from normal transactions (at least in the case where there is no refund transaction).
The purpose of this spike is to review <<Sanchez18a>>, take important notes, and describe how we can use <<kzen_multi_hop_locks>> to implement the idea.

== Protocol Overview

Let P1 and P2 have a joint public key X = g^x~1~x~2~^ and x~1~ and x~2~ are their respective private keys and assume the following situation:

- P2 knows some value y and wishes to get a signature on a message 𝓂 under the joint public key X.
- P1 knows g^y^ but wants to know y.

So they make a deal.
P1 will provide her half of the signature on 𝓂 as long as she is guaranteed to learn y if she sees the completed signature (note that she's going to be able to see the completed signature because it will be on the blockchain).
y plays a similar role as the hash preimage in an HTLC.
Note that in <<Sanchez18a>≻ y is denoted as α.

== Key Generation

=== Generating the joint nonce R

When signing, like in <<Lindell17>>, P1 and P2 need to agree on a joint nonce R, except that instead of R = g^r~1~r~2~^ we have R = g^r~1~r~2~y^.

First P2 sends g^y^ to P1.
It is important to do this first to avoid breaking the simulation by letting P2 choose g^y^ adaptively.

After that, P1 and P2 have exchange R~1~ = g^r~1~^ and R~2~ = g^r~2~^ via the usual simulatable Diffie-Hellman coin flipping in <<Lindell17>> (actually not see implementation note below).

Next, P2 sends R~3~ = R~2~^y^ and a proof that (g^y^, R~2~, R~3~) is a valid Diffie-Hellman triple.
Note, I think that he could actually just send this when he sends R~2~ during the coin flipping but I'm unsure whether the two things can happen in parallel without breaking the simulation.

The proof for a valid Diffie-Hellman triple used in <<kzen_multi_hop_locks>> works by proving knowledge of a pre-image y for the one-way homomorphism f(y) = (g^y^, R~2~^y^) through the Sigma protocol.
This proves that (g^y^, R~2~, R~3~) is a valid Diffie-Hellman triple.
I found a nice explanation of this in <<Maurer09>> (section 6.6).

=== Implementation Notes

The proof for a valid Diffie-Hellman triple is implemented here: https://github.com/KZen-networks/curv/blob/18f0081a9a3025eafd49ad496e5032647edf4aa3/src/cryptographic_primitives/proofs/sigma_ec_ddh.rs
and is non-interactive via Fiat-Shamir transform of the Sigma protocol.

The coin flipping to determine R actually uses this Diffie-Hellman NIZΚ instead of the Schnorr NIZK used in the key generation (note that Diffie-Hellman proof is like a Schnorr proof for two bases in parallel).
The argument is that doing the Diffie-Hellman NIZK for knowledge of x s.t. f(x) = (g^x^, h^x^) where the prover doesn't know α s.t. h = g^α^ proves the statement under the "knowledge of exponent" assumption without having to apply rewinding techniques (i.e. using [forking lemma](https://en.wikipedia.org/wiki/Forking_lemma))
This idea is suggested in <<Lindell17>> (section 4.3) as way to make the signing protocol in parallel without violating the security proofs (under the "knowledge of exponent" assumption).

== Signing

The signing protocol then continues as normal under R except at the final output is no longer a valid signature (it's missing y).
We'll call this incomplete signature s′′ as in <<Sanchez18a>>

P1 now sends s′′ to P2.
P2 can now finally calculate the final `s` from s′′ using his knowledge of y.
Specifically `s` = y^-1^(s′′).

When `s` is revealed to P1, she can extract y = s^-1^s′′ (note in <<Sanchez18a>> the paper it says y = (s(s′′^-1^))^-1^ but this is slower).

Well almost.
The (R,s) signature that makes it into the Bitcoin or Ethereum Blockhain isn't necessarily the one you will be able to extract y from directly.
This is because (R, -s) is also a valid signature.
There is a soft fork proposal in Bitcoin to fix this: [BIP146](https://github.com/bitcoin/bips/blob/master/bip-0146.mediawiki), but we have to make sure that the code doesn't break if you receive a signature with a "high s".
This isn't mentioned in <<Sanchez18a>> but it is recognized in <<Sanchez18b>>.
You will have to try both y and -y to see which one is the real y.

=== Implementation Notes

This will have to implemented by us, but it may be helpful to follow along with：https://github.com/KZen-networks/multi-hop-locks to see how they did it for the multi-hop lock case.

[bibliography]
== References

- [[[Lindell17]]] Fast Secure Two-Party ECDSA Signing: https://eprint.iacr.org/2017/552.pdf
- [[[Sanchez18a]]] Scriptless Scripts with ECDSA: https://lists.linuxfoundation.org/pipermail/lightning-dev/attachments/20180426/fe978423/attachment-0001.pdf
- [[[Sanchez18b]]] Anonymous Multi-Hop Locks for Blockchain Scalability and Interoperability: https://eprint.iacr.org/2018/472.pdf
- [[[kzen_multi_hop_locks]]] KZen's ECDSA multi hop locks implementation: https://github.com/KZen-networks/multi-hop-locks
- [[[Maurer09]]] Unifying Zero-Knowledge Proofs of Knowledge: ftp://ftp.inf.ethz.ch/pub/crypto/publications/Maurer09.pdf
