= Improving privacy through onion routing over libp2p
Daniel Karzel <daniel.karzel@coblox.tech>;
:toc:
:revdate: 2019-06-17

NOTE: Author: {authors} +
Date: {revdate} +
Tracking issue: https://github.com/coblox/spikes/issues/8[Tor Support for COMIT]

== Context

Onion routing as implemented by the https://en.wikipedia.org/wiki/Tor_(anonymity_network)[Tor network] enables anonymous usage of the internet
through end2end multi-time-encryption over multiple hops provided through relay nodes. Anybody in the network can set up a relay node in the network.

Onion routing would help to create more privacy through anonymity in the comit network.


== Research

=== Onion Routing over libp2p

==== IPFS issues tracking onion routing over libp2p

IPFS is working on integrating onion routing over libp2p:

- Discussion on the topic from the IPFS notes:
  * https://github.com/ipfs/notes/issues/37

- Resulting up-to-date issue "Anonymous IPFS"
  * https://github.com/ipfs/go-ipfs/issues/6430

We might run into similar issues as described in https://github.com/ipfs/go-ipfs/issues/6430[IPFS issue #6430].

Might be a good idea to reach out to the IPFS team.

===== Collection of implementations

IMPORTANT: Most of the projects listed here are in a prototype/proof-of-concept stage. Decision needed on how to proceed with that.

- OpenBazaar repo for onion routing on IPFS (go-lang):
  * https://github.com/OpenBazaar/go-onion-transport/

- Protoype POC implementation of onion routing over libp2p (go-lang):
  * https://github.com/t-bast/go-libp2p-echalotte

- Web3 Foundation is tacking the issue here:
  * https://github.com/w3f/messaging
  * Protocol requirement details here: https://github.com/w3f/messaging/blob/master/REQUIREMENTS.md
  * The following entry (HOPR) is a result of this initiative

 - HOPR by Validity labs:
  * https://github.com/validitylabs/messagingProtocol
  * includes payment for relay nodes, not sure if that would suit our needs

==== libp2p extensions enabling onion routing

libp2p has two protocols in the making that will provide certain functionality that can be useful to enable onion routing:

1. Rendezvous point
  * https://github.com/libp2p/specs/blob/master/rendezvous/README.md
2. Circuit relay
  * https://github.com/libp2p/specs/blob/master/relay/README.md

Relays are currently implemented in the js and the go version of libp2p only.

=== Garlic routing and I2P as an alternative

https://geti2p.net/en/about/intro[I2P] implements a variant of onion routing called https://en.wikipedia.org/wiki/Garlic_routing[garlic routing].

- Rust I2P engine:
  * https://github.com/str4d/ire

IMPORTANT: Work out the difference to onion routing, decision needed what is more suitable for comit.

=== Channeling Comit traffic through Tor

Sending libp2p TCP packages over the Tor network (transport layer).

One possibility would be to start an instance of Tor (without the browser) together with Comit and route the Comit traffic through Tor.
It has to be evaluated how libp2p would react to this.

- Configuring an onion service:
  * https://2019.www.torproject.org/docs/tor-onion-service.html.en

- Tor manual startup options
  * https://2019.www.torproject.org/docs/tor-manual.html.en

- Discussion on channelling traffic through Tor's SOCKS port
  * https://www.reddit.com/r/TOR/comments/7mhlp9/how_to_route_an_arbitrary_application_through_the/

==== libp2p as pluggable transport for the Tor network

Another possible way to achieve this could be pluggable transport, which is a relatively new concept within the Tor community.
How exactly this could be achieved with libp2p remains open.

- Discussion on libp2p as pluggable transport for Tor (ticket stale since 2017)
  * https://github.com/libp2p/libp2p/issues/17

- Introduction to plugable transport in Tor:
  * https://trac.torproject.org/projects/tor/wiki/doc/PluggableTransports


=== Random other information

Hackernews on relays in libp2p and Tor-meek (interesting reads, but somewhat unrelated)
https://news.ycombinator.com/item?id=14295993

Side-node on Tor and TLS:
https://security.stackexchange.com/questions/75975/is-tls-in-tor-useless

=== Solution Proposal

WARNING: To be filled out after more research was done.

==== Open question collection:

1. If comit implements onion routing: How many relays are actually needed in order to make this work in a meaningful way?
2. Would it be possible to leverage the existing Tor network rather then just implementing onion routing in comit?
(e.g. provide relays to the Tor network rather than implementing the protocol)
3. Both libp2p and Tor operate (not exclusively...) over TCP, but (how exactly) could they be brought together?
Does it work to just channel the complete traffic into Tor's SOCKS port?

=== Next steps:

1. Test if channelling all traffic through running Tor's onion services works with Comit using libp2p.
2. Evaluate if that solution actually adds the level of anonymity we want to achieve.
