= NAT Traversal
Rishab Sharma<rishab.sharma@tenx.tech>;
:toc:
:revdate: 2020-03-15

NOTE: Author: {authors} +
Date: {revdate} +
Tracking issue: https://github.com/comit-network/comit-rs/issues/1172[#1172]

== Abbreviations

NAT: Network Address Translation/Translator

UPnP: Universal Plug and Play

TURN: Traversal Using Relays around NAT

STUN: Session traversal utilities around NAT

== Context

NAT allows the use of private IP addresses on private networks behind routers with a single public IP address facing the Internet.
This can make it difficult for a comit node to determine a public address that can be used to receive inbound connections.
This documents evaluates a number of NAT traversal methods that allow a comit node to connect to another comit node situated behind a NAT.

== Goals

1. Allow a comit node to traverse a NAT to reach another comit node.

== NAT Traversal Methods

This sections provides an overview and evaluation of current NAT traversal methods.
In these examples, unless stated otherwise, Alice is dialing Bob who is behind a NAT.

=== Manual Port Forwarding

Bob configures his NAT to forward data received from an publicly facing port and IP address to the private IP address of device.
Bob notifies Alice that he can reached through the aforementioned publicly facing port and IP address.

This solution does not require any changes to the COMIT codebase and places the burden on the user to configure their NAT.
Users who do not have control over the configuration of their NAT can not use this method.
We cannot completely rely on port forwarding because users on mobile, shared or corporate managed networks will not have access to NAT configuration.

- + Alice and Bob can communicate through a direct connection

- - Requires Bob to have access to NAT configuration

- - Requires Bob to configure his NAT


=== Automatic Port Forwarding using UPnP

A UPnP enabled NAT automatically forwards publicly facing ports as requested by an application.
Unlike manual port forwarding, Bob is not required to configure his NAT.
Not all NATs are UPnP capable and it is often disabled or not used by peer to peer applications.
Bitcoin core removed UPnP support due to security concerns: https://bitcoin.org/en/alert/2015-10-12-upnp-vulnerability.

- + Does not require Bob to configure his NAT

- + Alice and Bob can communicate through a direct connection

- - Requires the user to have a UPnP capable and enabled NAT (UPnP capable routers are fairly common in home networks)

- - Opens up the user to security vulnerabilities arising from the NAT blindly trusting applications and allowing to open externally facing ports

=== Reverse connection

Instead of Alice attempting to reach Bob through his NAT. Bob dials Alice and Alice uses the connection to send to data to Bob.
This technique only works if Alice knows her public IP and port and has provided it to Bo.
Since Alice is unable to dial Bob, Alice is unable to initiate communication and must wait to be dialled by a Bob.

Reverse connections cannot be used because many of our protocols require both peers to be able to initate a connection with each other.
This means that COMIT protocols will have to redesigned to use the connection initiated by dialer to complete an atomic swap.
Peers behind a NAT will be unable to play an active role in the COMIT network.

- + Does not require Bob to configure his NAT

- + Does not require the user to have access to NAT configuration

- + Alice and Bob can  communicate through a direct connection

- - Alice can not dial Bob and therefore cannot initiate a swap or use Bob as a peer to propagate information to the network

- - We will most likely need to redesign protocols to utilise reverse connections

- - Requires Bob to have a known external IP

=== STUN/Hole Punching

Bob sends UDP messages to a third peer known as a STUN server.
The STUN server will return which ports and public IP Bobs's UDP messages originated from.
Bob has now discovered public IP and ports which peers can use to dial him.
Bob can provide this knowledge to Alice, allowing Alice to dial him.

STUN cannot be used to traverse NAT configurations that randomly assign a port and/or IP for new connections.
For example, a symmetric NAT will randomly generate a new port and/or public IP for each outbound connection made by Alice.
This prevents Bob from determining or predicting the external IP and ports assigned to her by the NAT.

- + Does not require Bob to configure his NAT

- + Alice and Bob can communicate through a direct connection

- - Cannot traverse symmetric, cone and restricted cone type NATs

- - Requires a third peer to start a connection between Alice and Bob

- - Requires the third peer to know its public IP and ports (either through another STUN/TURN or port forwarding)

- - Requires peers to know peers that are STUN servers

- - Leads to some degree of centralisation

=== TURN

When Bob isn’t able to determine or predict his public facing IP address and port, Bob can dial out to a relay peer, which will keep a long-lived connection open.
Other peers will be able to dial through the relay peer, which will forward traffic to Bob.

- + Can be used to traverse all commonly know NAT configurations

- + Does not require the Bob to configure his NAT

- - Requires a third peer to serve as a relay for communications between Alice and Bob

- - Requires the third peer to have an externally facing IP address

- - Requires a third peer to serve as a relay for communications between Alice and Bob

- - Requires peers to know peers that are TURN servers

- - Leads to some degree of centralisation

== Recommendation

Assumption: A significant portion of comit nodes will have forwarded ports.

We should implement the following NAT traversal methods in the order listed below.
After each implementation we should evaluate whether it is necessary to implement the subsequent NAT traversal methods.

1. TURN (essential for maximum NAT coverage)
2. STUN (optional to reduce load and reliance on TURN servers)
3. UPnP (optional to reduce load and reliance on TURN servers)

TURN is the first prioirty as it is capable of traversing most commonly known NAT configurations.
In order for TURN to work, some port forwarded peers will have to operate as TURN servers to allow NAT restricted peers to communicate.

The libp2p specification defines a circuit relay module based off the TURN protocol.
This protocol allows NAT restricted nodes to "proxy" through other p2p nodes that volunteer to act as p2p-circuit relays.
These nodes will announce to the network that they are accepting relay connections using libp2p's peer routing.
Currently there is no Rust implementation of the circuit relay module but the Javascript and Go implementations could be used as a guide.

STUN would be implemented if we found that there are insufficient nodes willing to act as relays due bandwidth concerns.
STUN allows peers to discover their public IP and ports and establish a communicate directly without a relay.

libp2p has it's own version of the STUN protocol using peer-routing, identify, and reuseport.

1. reuseport uses the same source port for both dialing and listening allowing us to accept new inbound connections on the source port used by the router
2. identify receives observed address information from all connected peers
3. peer-routing allows us to publish these addresses to the network and allow peers to discover their own public address on which they can accept inbound connections

If both STUN and TURN are implemented, STUN will be the preferred method and TURN will be used as a fallback if the public address cannot be determined or predicted using STUN.

Lastly we could implement a UPnP module similar to https://github.com/libp2p/go-libp2p-nat if we found that many users were relying on TURN servers instead of manually port forwarding.
This would reduce the load on TURN servers and centralisation of the network.

== Sources

- Wikipedia article on common NAT classifications: https://en.wikipedia.org/wiki/Network_address_translation#Methods_of_translation
- Twilio overview of STUN, TURN and ICE protocols for NAT traversal: https://www.twilio.com/docs/stun-turn/faq
- IPFS tutorial on libp2p's circuit relay: https://github.com/ipfs/js-ipfs/blob/master/examples/circuit-relaying/README.md
- libp2p circuit relay spec:  https://github.com/libp2p/specs/tree/master/relay
- libp2p identify spec: https://github.com/libp2p/specs/tree/master/identify
- Nat traversal discussion thread for go-libp2p: https://github.com/libp2p/go-libp2p/issues/375
