@startuml
' hide the spot
hide circle

!include https://raw.githubusercontent.com/comit-network/spikes/master/assets/db_schema/all_entities.iuml!herc20_swap_protocols
!include https://raw.githubusercontent.com/comit-network/spikes/master/assets/db_schema/all_entities.iuml!herc20_swap_protocols_connections
!include https://raw.githubusercontent.com/comit-network/spikes/master/assets/db_schema/all_entities.iuml!herc20_swap_protocols_state
!include https://raw.githubusercontent.com/comit-network/spikes/master/assets/db_schema/all_entities.iuml!herc20_swap_protocols_connections_state

' for local use
'!include all_entities.iuml!herc20_swap_protocols
'!include all_entities.iuml!herc20_swap_protocols_state
'!include all_entities.iuml!herc20_swap_protocols_connections
'!include all_entities.iuml!herc20_swap_protocols_connections_state

@enduml
